name: Write Comment on Push 1

on:
  pull_request_target:
    types: [opened]  

permissions:
  issues: write

jobs:
  write_to_comment:
    runs-on: ubuntu-latest  # Specifies the runner.
    steps:
      - name: Leave a comment on the Issue6
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const message = "Hola mundo 2.1";
            github.rest.issues.createComment({
              owner: "MIT-Bitcoin-2024",
              repo: "gha-tut",
              issue_number: "1",
              body: message
            }); 