name: Review - Check Payment

on:
  pull_request_review:
    types: [submitted]

# permissions:
#   issues: write
#   pull-requests: write

jobs:
  make_request:
    runs-on: ubuntu-latest
    steps:
  
      - name: Hello World Step
        run: echo "Hello, World!"
